version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "C:\\data"
        target: "C:\\data"
        consistency: consistent